project_id = "re-post-v2"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
